### ISSUE TITLE
imgui的内存占用问题

### ISSUE THREAD

**Issue by wuhanhui** [SaierMe/piv#1]
非常感谢作者的开源。目前运行云盘试例的imgui win32窗口，内存占用大约是140M，而imgui官方的win32 direct11的内存占用25M。这差距也太大了，是哪里有问题吗

**Comment by SaierMe** [comment]
经过对比测试，主要占内存的是中文字体微软雅黑，不加载中文字体则只占 16M 内存。

**Comment by wuhanhui** [comment]
非常感谢。回复如此快速。请问有没有交流QQ或者微信群

**Comment by SaierMe** [comment]
目前我没有建群，可以在火山官方3群或利快云的群里找到我
