### ISSUE TITLE
一个小BUG

### ISSUE THREAD

**Issue by 341991** [SaierMe/piv#2]
piv/src/piv_NtProcess.hpp
1005行
if (ProInfo->isWow64 && !Nt.NtWow64WriteVirtualMemory64)
Nt.NtWow64WriteVirtualMemory64 不应该取反，这会导致write_memory一直返回false
今天发现NT进程操作类，写内存无论如何就是失败，翻了下源码这里有个小BUG

**Comment by SaierMe** [comment]
收到
